### ISSUE TITLE
IDL Compile Question About Article

### ISSUE THREAD

**Issue by 10cks** [Prepouce/CoercedPotato#2]
Dear friends, I read your article, it's very helpful to learn about Potato. But when I try to make MS-EFSR idl files (.c file and .h file), the header files and c files I generated are very different from yours.The file I generated will not compile correctly, I don't know which operation of mine is wrong, I hope you can help me check it, thank you very much.
This is my files address: https://github.com/10cks/IDL-files

**Comment by 10cks** [comment]
I followed exactly what I did in the article, such as removing import and adding definitions at the beginning of the file

**Comment by Hack0ura** [comment]
Hi, thank you for your feedback about the article ! :smile:  
Your IDL file seems to be OK, I just wonder if putting some type definitions at the beginning of your file and not in the interface definition directly cannot brings some unknown issues, but I don't think this is the problem. 

What is exactly the error you get ? If it is something like this : 
![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/621d0f7c-6590-480c-9db3-0c410758b72c)

Then, you are on the way to get your file correctly compiled! :smiley: We forgot to explain this part in the article, but most of the time, after compiling an IDL file, some definitions are already defined in the libraries you include, so it generates conflicts.You just need to remove definitions that are causing troubles of your header file, and it will work! 
The problem is that you cannot compile the IDL file without these definitions. So you have to add it, and then remove if conflicts appears.

For information, we are using Visual Studio 2022, others versions may have different behaviors. Never tried.

I hope it helped you ! :smiley: And don't hesitate if you have more questions! :wink:

**Comment by 10cks** [comment]
Thank you for your reply, I according to you provide solutions that can solve the mistake, but I found a problem: I generated file contains functions function 'EfsRpcQueryRecoveryAgents' less than you, is this manually add?

**Comment by 10cks** [comment]
I also see some extra functions in your header file, such as proc * below, what does this do? Was it added manually?
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/cd7d5051-60c8-44a3-869d-b17072afb83e)

**Comment by Hack0ura** [comment]
Concerning EfsRpcQueryRecoveryAgents, it should be there, as it is defined in the IDL file : 
![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/0cb4aaea-2185-42d8-9eba-26d77f23c5f2)

**Comment by 10cks** [comment]
Ok, I have no more questions at the moment. Please allow me to thank you again for your articles, which have benefited me a lot.

**Comment by 10cks** [comment]
I have another question that has nothing to do with compiling idl:
According to the documentation provided by coercer, take 'EfsRpcOpenFileRaw' function for example:
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/fea8c93e-5189-4db7-bb59-8f22340ef002)

pipeserver name can use 'efsrpc' or 'lsarpc' and so on, but when I change pipeserver listener like:
```
\\\\.\\pipe\\xxxx\\pipe\\efsrpc
```
It doesn't work correctly. PipeName only use 'srvsvc' can be successfully executed. I am puzzled about this point, do not know if I missed any knowledge.

**Comment by Hack0ura** [comment]
Yes, you have misunderstand one small thing : 
Each RPC method is defined by an RPC interface. This RPC interface can be accessed using different protocols : RPC directly, RPC over IP, or RPC over named pipe (and probably a lot of others defined in the documentation). When we want to use an RPC method that is vulnerable, we need to bind to an RPC interface, which is what we do here in the code : 
![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/e4246dbe-99b7-4a54-a568-e61e28c02a9c)
In our program, we decided to use the protocol **ncalrpc** which stands for **RPC via Local Procedure Call**. It is used to perform RPC calls locally, which was easier to develop because everything is done dynamically. 
However, we could have used a known named pipe to connect to the RPC interface and call the RPC methods we wanted to use. We would have used the protocol **ncacn_np**.

Now, the fact that we listen on **srvsvc** is because when we call a vulnerable RPC method, it is the pipe named that the RPC call tries to trigger. And it can be seen with ProcessMonitor. For example, if you bind to the RPC interface MS-RPRN, then you call RpcRemoteFindFirstPrinterChangeNotification(), the normal behavior of this function is to trigger /pipe/spoolss. But you can control this value. So, by using the bug with "/", the Windows system validates and corrects the path and adds the "normal" named pipe at the end. That's why we need to listen on /pipe/whatever/pipe/spoolss. 

So for each RPC function of the program, I checked ProcessMonitor to see if a trigger is done on a specific named pipe.

Hope it helped you understanding better :wink:

**Comment by 10cks** [comment]
This is how I understand it:
If I am using the ncacn ip tcp protocol in createRPCbind, a namepipe provided by 'access' in the coercer supplied document, such as efsrpc, could trigger the pipe in pipeserver, just like 'srvsvc' In the current code.

Is that correct?

**Comment by 10cks** [comment]
I went to read this security researcher's article ([itm4n](https://itm4n.github.io/from-rpcview-to-petitpotam/)),Even with the ncacn_np protocol, pipeserver still need listens to srvsvc. The most confusing point for me at the moment is what is the meaning of the information in the document provided by coercer, as in my image above.What does "access" mean in a document?
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/defed3c4-268a-47fc-b803-52ebeaa8b92d)
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/eedc4379-36b8-464b-8d42-cc6ca136ddca)

**Comment by 10cks** [comment]
This is the implementation process in my opinion. Is there any problem?
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/89f57151-cdda-4424-9f79-8838a7a4286f)

**Comment by Hack0ura** [comment]
No, the protocol sequence used to create the RPC bind does not change the named pipe you need to listen to because the protocol sequence just allows you to call the RPC methods you want to use.
The fact that srvsvc is trigged is because it is the "normal" behavior, just how Itm4n shows it here : 
![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/b72a72d6-8eae-40e4-b031-9f9cc050f6d4)

By testing each known vulnerable RPC function of MS-EFSR, it appears that each function needs to connect to the named pipe /PIPE/srvsvc before doing what it is defined to do. So in a normal use of EfsRpcOpenFileRaw for example, lsass.exe would request /PIPE/srvsvc and then open the requested encrypted object. However, by adding "/" in the path, we can make lsass.exe trigger another path that we can control. But it doesn't relies on how you create a handle on the RPC interface! It just depends on which RPC function you use, once you have your handle.

I hope it helped you to better understand how it works :smile:

**Comment by 10cks** [comment]
Thank you very much for your patient reply, which has enabled me to learn a lot of knowledge. At present, my coercer problem lies in the meaning of "access" in the document provided by COERcer. What does it do?
![image](https://github.com/Prepouce/CoercedPotato/assets/47177550/1790d784-0718-4f66-bcbc-0373eab56cf4)

**Comment by Hack0ura** [comment]
No problem haha, I can understand it's a bit tricky to understand, it is not very intuitive :smile: 

"access" in this document means "the ways to bind to MS-EFSR interface". But it will depend of the system you are using. For example, on a Windows Server 2016, lsass.exe implements all these RPC interfaces and each RPC interface is identified by a unique UUID as defined in the documentation : 

![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/e08cdd33-ede4-4843-9521-5d6d3a4d715f)

And you can see here all the endpoints that are listening : 

![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/9ae959ca-1f40-4fd1-bb85-89fc2bf4b94e)

So it means that, to bind to one specific RPC interface implemented by lsass.exe, you need to use one of these endpoints to create an RPC bind. But you are free to select the one you want to use. Now, if I look at a domain controller, the listening endpoints are a bit different, yet I am looking at the same process (lsass.exe) : 

![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/6d3ac6f2-4d76-471a-b3f9-ba6f67584f4b)

So, on a domain controller, I could use \PIPE\efsrpc to bind to MS-EFSR and call a vulnerable RPC function. It would also work.

Finally, the pipe \PIPE\srvsvc is launched by the process svchost.exe, which implements some other RPC interfaces :  

![image](https://github.com/Prepouce/CoercedPotato/assets/144810923/73c03dd3-644b-4d93-97c3-08b7c7a95b7b)

But I have never checked which RPC functions are implemented in there, may be interesting! You can use RpcView to have a better understanding about this if you want to.

Hope it helped :wink:

**Comment by 10cks** [comment]
I get it. Thank you.
